# Generated by Django 2.0.3 on 2018-03-28 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_book_user_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user_author',
        ),
    ]
